Chapter 3 - Recursion
Seng-Jik/Functional-Magic-Book pull request #13
Opened 2020-10-02 18:52 UTC by Seng-Jik

- [ ] 介绍“尾递归优化”
- [ ] 介绍“递归出口”的概念

2020-10-11 14:27 UTC, HoshinoTented commented on 3.递归.md
> +为了方便描述，我们在这里将会引入“模式匹配（Partten Matching）”语法来更清晰地描述这个函数，关于模式匹配的语法，请参阅*https://docs.microsoft.com/zh-cn/dotnet/fsharp/language-reference/pattern-matching*，之后我们便可写出这样的代码：
> 关于模式匹配的语法，请参阅*https://docs.microsoft.com/zh-cn/dotnet/fsharp/language-reference/pattern-matching*

是否应该用类似于 [1] 这种的 “参考，引用” （忘记叫什么了）呢？

2020-10-11 14:27 UTC, HoshinoTented commented on 3.递归.md
> +F#提供了`rec`关键字，使得你可以在函数的定义中访问它自身：
好奇的读者可能会想知道这是如何实现的，后面会介绍吗？
或者介绍实现可能超纲？

2020-10-11 14:27 UTC, HoshinoTented commented on 3.递归.md
> +let list1 = [ 1; 2; 3; 4; 5 ]
建议对 list1 和 list2 （最好 list3 也要）加上注释说明

2020-10-11 14:27 UTC, HoshinoTented commented on 3.递归.md
> +
希望在这里加上输出
虽然说可能算是鼓励读者自己敲代码运行？
但感觉还是加上输出好点
下同

2020-10-11 14:27 UTC, HoshinoTented commented on 3.递归.md
> +    while true do
前面的章节还没有介绍 `while`

2020-10-11 14:27 UTC, HoshinoTented commented on 3.递归.md
> +### 对列表求和
下面的代码都没有高亮

2020-10-11 14:27 UTC, HoshinoTented commented on 3.递归.md
> +printfn ”%A" (selectEven [1..5])
引号应该是英文引号，这里使用了中文引号

2020-10-11 14:27 UTC, HoshinoTented commented on 3.递归.md
> +| a::tail -> tail @ [a]
这里的 `@` 是做什么用的呢？

2020-10-12 06:50 UTC, Seng-Jik commented on 3.递归.md
> +F#提供了`rec`关键字，使得你可以在函数的定义中访问它自身：
介绍实现会超纲，而且它的实现并不是一个非常干净的实现。

2020-10-12 06:53 UTC, Seng-Jik commented on 3.递归.md
> +为了方便描述，我们在这里将会引入“模式匹配（Partten Matching）”语法来更清晰地描述这个函数，关于模式匹配的语法，请参阅*https://docs.microsoft.com/zh-cn/dotnet/fsharp/language-reference/pattern-matching*，之后我们便可写出这样的代码：
因为这里模式匹配是非常重要的语法，属于前置知识，需要明显强调，不适合使用“参考”语法。

2020-10-12 07:21 UTC, ICEYSELF commented on 3.递归.md
> +为了方便描述，我们在这里将会引入“模式匹配（Partten Matching）”语法来更清晰地描述这个函数，关于模式匹配的语法，请参阅*https://docs.microsoft.com/zh-cn/dotnet/fsharp/language-reference/pattern-matching*，之后我们便可写出这样的代码：
那很明显这里也不适用链接。你应该把模式匹配的用法抄过来，而不是参阅XXX。

2020-10-12 07:39 UTC, ICEYSELF requested changes

2020-10-12 07:39 UTC, ICEYSELF commented on 3.递归.md
> +当递归的调用在尾部时，编译器可以将其展开为循环，因此在面对尾递归时，可以不考虑其递归终止条件和递归出口的问题。
我们似乎还没介绍过“循环”。既然Lambda calculus都有了，为什么不用LC来解释尾递归优化的工作原理，而是走到了imperative的邪路上

2020-10-12 07:39 UTC, ICEYSELF commented on 3.递归.md
> +```
这个地方需要一些注解。

2020-10-12 07:39 UTC, ICEYSELF commented on 3.递归.md
> +	invalidArg "x" "f(x) does not exists!"
does not exist

2020-10-12 07:39 UTC, ICEYSELF commented on 3.递归.md
> +    | _ -> invalidArg "x" "f(x) does not exists!")
Тоже.

2020-10-12 07:39 UTC, ICEYSELF commented on 3.递归.md
> +
I can't agree more.

2020-10-12 07:39 UTC, ICEYSELF commented on 3.递归.md
> +
最好有个图来详细描述一下列表。就像
![learn-you-a-haskell/cha2/intro-to-list](http://s3.amazonaws.com/lyah/listmonster.png)

而且这里关于列表给的描述实在是太少了，建议看一下Learn You a Haskell, Realworld Haskell和SICP是怎么介绍列表的

2020-10-12 08:25 UTC, ICEYSELF commented on 3.递归.md
> +为了方便描述，我们在这里将会引入“模式匹配（Partten Matching）”语法来更清晰地描述这个函数，关于模式匹配的语法，请参阅*https://docs.microsoft.com/zh-cn/dotnet/fsharp/language-reference/pattern-matching*，之后我们便可写出这样的代码：
何况这个链接里的文档是机翻的，还存在肉眼可见的错误

2020-10-25 08:24 UTC, Simakeng approved these changes

2021-02-14 07:00 UTC, Seng-Jik commented on 3.递归.md
> +
已经增补了关于列表概念的介绍

2021-02-14 07:02 UTC, Seng-Jik commented on 3.递归.md
> +当递归的调用在尾部时，编译器可以将其展开为循环，因此在面对尾递归时，可以不考虑其递归终止条件和递归出口的问题。
使用“循环”对于熟悉命令式语言的人来说更为熟悉。

2021-02-14 07:16 UTC, ICEYSELF approved these changes

2021-02-14 07:16 UTC, ICEYSELF commented
LGTM

2021-02-14 14:54 UTC, merged